version: '3.9'

services:
  backend:
    container_name: Back
    build: ./final_project
    env_file:
      - ./final_project/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/final_project/
    depends_on:
      - frontend
      - psql

  psql:
    image: postgres:latest
    container_name: PSQL
    env_file:
      - ./final_project/.env
    volumes:
      - ./final_project/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  celery_worker:
    build: ./final_project
    container_name: Celery_worker
    env_file:
      - ./final_project/.env
    volumes:
      - ./final_project:/app
    entrypoint: ["celery", "-A", "final_project", "worker", "--loglevel=info"]
    depends_on:
      - backend
      - redis

  celery_beat:
    build: ./final_project
    container_name: Celery_beat
    env_file:
      - ./final_project/.env
    volumes:
      - ./final_project:/app
    entrypoint: [ "celery", "-A", "final_project", "beat", "--loglevel=info" ]
    depends_on:
      - backend
      - redis

  redis:
    image: redis:latest
    container_name: Redis
    volumes:
      - ./final_project:/app
    ports:
      - "6379:6379"

  frontend:
    container_name: Front
    build: ./fproject_front
    ports:
      - "8080:8080"
    volumes:
      - ./fproject_front:/front_code

